In [6]:
import pandas as pd

In [7]:
import numpy as np

In [12]:
s1 = pd.Series([2,4,8,16,32,64] , index=['onetime','twotime','threetime','fourtime','fivetime','sixtime'])


In [13]:
s1

onetime       2
twotime       4
threetime     8
fourtime     16
fivetime     32
sixtime      64
dtype: int64

In [14]:
s1.values

array([ 2,  4,  8, 16, 32, 64], dtype=int64)

In [15]:
s1.index

Index(['onetime', 'twotime', 'threetime', 'fourtime', 'fivetime', 'sixtime'], dtype='object')

# values with lables or index of series

In [18]:
s1[1:3]

twotime      4
threetime    8
dtype: int64

In [19]:
s1[1:3].values

array([4, 8], dtype=int64)

In [20]:
s1["twotime":"fivetime"]

twotime       4
threetime     8
fourtime     16
fivetime     32
dtype: int64

In [21]:
s1["twotime":"fivetime"].values

array([ 4,  8, 16, 32], dtype=int64)

In [44]:
students = [
    {"ROLL-NUMBER": 4, "NAME": "ABDIL MOIZ", "DEPARTMENT": "CYBER SECURITY", "BATCH": 22, "AGE": 26, "RESULT": "Passed"},
    {"ROLL-NUMBER": 5, "NAME": "MUNEEB UR REHMAN", "DEPARTMENT": "CYBER SECURITY", "BATCH": 22, "AGE": 16, "RESULT": "Passed"},
    {"ROLL-NUMBER": 7, "NAME": "SALMA AIJAZ", "DEPARTMENT": "CYBER SECURITY", "BATCH": 22, "AGE": 21, "RESULT": "Passed"},
    {"ROLL-NUMBER": 34, "NAME": "MATIULLAH KHAN", "DEPARTMENT": "CYBER SECURITY", "BATCH": 22, "AGE": 30, "RESULT": "Failed"},
    {"ROLL-NUMBER": 12, "NAME": "ALI RAZA", "DEPARTMENT": "SOFTWARE ENGINEERING", "BATCH": 23, "AGE": 22, "RESULT": "Passed"},
    {"ROLL-NUMBER": 15, "NAME": "SARA KHAN", "DEPARTMENT": "SOFTWARE ENGINEERING", "BATCH": 23, "AGE": 17, "RESULT": "Passed"},
    {"ROLL-NUMBER": 21, "NAME": "AHMED KHAN", "DEPARTMENT": "INFORMATION TECHNOLOGY", "BATCH": 24, "AGE": 22, "RESULT": "Passed"},
    {"ROLL-NUMBER": 22, "NAME": "FAIZA ALI", "DEPARTMENT": "INFORMATION TECHNOLOGY", "BATCH": 24, "AGE": 21, "RESULT": "Failed"},
    {"ROLL-NUMBER": 31, "NAME": "ZAINAB AHMED", "DEPARTMENT": "COMPUTER SCIENCE", "BATCH": 25, "AGE": 20, "RESULT": "Passed"},
    {"ROLL-NUMBER": 33, "NAME": "USMAN ALI", "DEPARTMENT": "COMPUTER SCIENCE", "BATCH": 25, "AGE": 32, "RESULT": "Passed"}
]


In [45]:
df = pd.DataFrame(students)

In [46]:
df

ROLL-NUMBER              NAME              DEPARTMENT  BATCH  AGE  RESULT
0            4        ABDIL MOIZ          CYBER SECURITY     22   26  Passed
1            5  MUNEEB UR REHMAN          CYBER SECURITY     22   16  Passed
2            7       SALMA AIJAZ          CYBER SECURITY     22   21  Passed
3           34    MATIULLAH KHAN          CYBER SECURITY     22   30  Failed
4           12          ALI RAZA    SOFTWARE ENGINEERING     23   22  Passed
5           15         SARA KHAN    SOFTWARE ENGINEERING     23   17  Passed
6           21        AHMED KHAN  INFORMATION TECHNOLOGY     24   22  Passed
7           22         FAIZA ALI  INFORMATION TECHNOLOGY     24   21  Failed
8           31      ZAINAB AHMED        COMPUTER SCIENCE     25   20  Passed
9           33         USMAN ALI        COMPUTER SCIENCE     25   32  Passed

In [47]:
df["ROLL-NUMBER"]   # selecting one colum no it will be series 

0     4
1     5
2     7
3    34
4    12
5    15
6    21
7    22
8    31
9    33
Name: ROLL-NUMBER, dtype: int64

In [48]:
type(df["ROLL-NUMBER"])

pandas.core.series.Series

In [49]:
#now selecting two or more cloums ---------for this you will have to make it a list 
#df["ROLL-NUMBER","BATCH"]  this wrong implementation
df[["ROLL-NUMBER","BATCH"]]

ROLL-NUMBER  BATCH
0            4     22
1            5     22
2            7     22
3           34     22
4           12     23
5           15     23
6           21     24
7           22     24
8           31     25
9           33     25

# how to rename the cloumns name like if any column name have space, capitals letter 

In [50]:
#i want to rename the column [name]
df = df.rename(columns={"NAME":"NAMES","ROLL-NUMBER":"ROLL_NUMBER"})

In [51]:
df

ROLL_NUMBER             NAMES              DEPARTMENT  BATCH  AGE  RESULT
0            4        ABDIL MOIZ          CYBER SECURITY     22   26  Passed
1            5  MUNEEB UR REHMAN          CYBER SECURITY     22   16  Passed
2            7       SALMA AIJAZ          CYBER SECURITY     22   21  Passed
3           34    MATIULLAH KHAN          CYBER SECURITY     22   30  Failed
4           12          ALI RAZA    SOFTWARE ENGINEERING     23   22  Passed
5           15         SARA KHAN    SOFTWARE ENGINEERING     23   17  Passed
6           21        AHMED KHAN  INFORMATION TECHNOLOGY     24   22  Passed
7           22         FAIZA ALI  INFORMATION TECHNOLOGY     24   21  Failed
8           31      ZAINAB AHMED        COMPUTER SCIENCE     25   20  Passed
9           33         USMAN ALI        COMPUTER SCIENCE     25   32  Passed

In [52]:
df.AGE.max()

32

In [53]:
df.AGE.min()

16

In [54]:
df.AGE.argmax()

9

In [59]:
df[df.AGE >= 20][["NAMES","DEPARTMENT"]]

NAMES              DEPARTMENT
0      ABDIL MOIZ          CYBER SECURITY
2     SALMA AIJAZ          CYBER SECURITY
3  MATIULLAH KHAN          CYBER SECURITY
4        ALI RAZA    SOFTWARE ENGINEERING
6      AHMED KHAN  INFORMATION TECHNOLOGY
7       FAIZA ALI  INFORMATION TECHNOLOGY
8    ZAINAB AHMED        COMPUTER SCIENCE
9       USMAN ALI        COMPUTER SCIENCE