In [6]:
import pandas as pd

In [7]:
import numpy as np

In [12]:
s1 = pd.Series([2,4,8,16,32,64] , index=['onetime','twotime','threetime','fourtime','fivetime','sixtime'])


In [13]:
s1

onetime       2
twotime       4
threetime     8
fourtime     16
fivetime     32
sixtime      64
dtype: int64

In [14]:
s1.values

array([ 2,  4,  8, 16, 32, 64], dtype=int64)

In [15]:
s1.index

Index(['onetime', 'twotime', 'threetime', 'fourtime', 'fivetime', 'sixtime'], dtype='object')

# values with lables or index of series

In [18]:
s1[1:3]

twotime      4
threetime    8
dtype: int64

In [19]:
s1[1:3].values

array([4, 8], dtype=int64)

In [20]:
s1["twotime":"fivetime"]

twotime       4
threetime     8
fourtime     16
fivetime     32
dtype: int64

In [21]:
s1["twotime":"fivetime"].values

array([ 4,  8, 16, 32], dtype=int64)

In [73]:
students = [
    {"ROLL-NUMBER": 4, "NAME": "ABDIL MOIZ", "DEPARTMENT": "CYBER SECURITY", "BATCH": 22, "AGE": 26, "RESULT": "Passed"},
    {"ROLL-NUMBER": 5, "NAME": "MUNEEB UR REHMAN", "DEPARTMENT": "CYBER SECURITY", "BATCH": 22, "AGE": np.nan, "RESULT": "Passed"},
    {"ROLL-NUMBER": 7, "NAME": "SALMA AIJAZ", "DEPARTMENT": "CYBER SECURITY", "BATCH": 22, "AGE": 21, "RESULT": "Passed"},
    {"ROLL-NUMBER": 34, "NAME": "MATIULLAH KHAN", "DEPARTMENT": "CYBER SECURITY", "BATCH": 22, "AGE": 30, "RESULT": "Failed"},
    {"ROLL-NUMBER": 12, "NAME": "ALI RAZA", "DEPARTMENT": "SOFTWARE ENGINEERING", "BATCH": 23, "AGE": np.nan, "RESULT": "Passed"},
    {"ROLL-NUMBER": 15, "NAME": "SARA KHAN", "DEPARTMENT": "SOFTWARE ENGINEERING", "BATCH": 23, "AGE": 17, "RESULT": "Passed"},
    {"ROLL-NUMBER": 21, "NAME": "AHMED KHAN", "DEPARTMENT": "INFORMATION TECHNOLOGY", "BATCH": 24, "AGE": 22, "RESULT": "Passed"},
    {"ROLL-NUMBER": 22, "NAME": "FAIZA ALI", "DEPARTMENT": "INFORMATION TECHNOLOGY", "BATCH": 24, "AGE": 21, "RESULT": "Failed"},
    {"ROLL-NUMBER": 31, "NAME": "ZAINAB AHMED", "DEPARTMENT": "COMPUTER SCIENCE", "BATCH": 25, "AGE": np.nan, "RESULT": "Passed"},
    {"ROLL-NUMBER": 33, "NAME": "USMAN ALI", "DEPARTMENT": "COMPUTER SCIENCE", "BATCH": 25, "AGE": 32, "RESULT": "Passed"}
]


In [74]:
df = pd.DataFrame(students)

In [75]:
df

ROLL-NUMBER              NAME              DEPARTMENT  BATCH   AGE  RESULT
0            4        ABDIL MOIZ          CYBER SECURITY     22  26.0  Passed
1            5  MUNEEB UR REHMAN          CYBER SECURITY     22   NaN  Passed
2            7       SALMA AIJAZ          CYBER SECURITY     22  21.0  Passed
3           34    MATIULLAH KHAN          CYBER SECURITY     22  30.0  Failed
4           12          ALI RAZA    SOFTWARE ENGINEERING     23   NaN  Passed
5           15         SARA KHAN    SOFTWARE ENGINEERING     23  17.0  Passed
6           21        AHMED KHAN  INFORMATION TECHNOLOGY     24  22.0  Passed
7           22         FAIZA ALI  INFORMATION TECHNOLOGY     24  21.0  Failed
8           31      ZAINAB AHMED        COMPUTER SCIENCE     25   NaN  Passed
9           33         USMAN ALI        COMPUTER SCIENCE     25  32.0  Passed

In [76]:
df["ROLL-NUMBER"]   # selecting one colum no it will be series 

0     4
1     5
2     7
3    34
4    12
5    15
6    21
7    22
8    31
9    33
Name: ROLL-NUMBER, dtype: int64

In [77]:
type(df["ROLL-NUMBER"])

pandas.core.series.Series

In [78]:
#now selecting two or more cloums ---------for this you will have to make it a list 
#df["ROLL-NUMBER","BATCH"]  this wrong implementation
df[["ROLL-NUMBER","BATCH"]]

ROLL-NUMBER  BATCH
0            4     22
1            5     22
2            7     22
3           34     22
4           12     23
5           15     23
6           21     24
7           22     24
8           31     25
9           33     25

# how to rename the cloumns name like if any column name have space, capitals letter 

In [79]:
#i want to rename the column [name]
df = df.rename(columns={"NAME":"NAMES","ROLL-NUMBER":"ROLL_NUMBER"})

In [80]:
df

ROLL_NUMBER             NAMES              DEPARTMENT  BATCH   AGE  RESULT
0            4        ABDIL MOIZ          CYBER SECURITY     22  26.0  Passed
1            5  MUNEEB UR REHMAN          CYBER SECURITY     22   NaN  Passed
2            7       SALMA AIJAZ          CYBER SECURITY     22  21.0  Passed
3           34    MATIULLAH KHAN          CYBER SECURITY     22  30.0  Failed
4           12          ALI RAZA    SOFTWARE ENGINEERING     23   NaN  Passed
5           15         SARA KHAN    SOFTWARE ENGINEERING     23  17.0  Passed
6           21        AHMED KHAN  INFORMATION TECHNOLOGY     24  22.0  Passed
7           22         FAIZA ALI  INFORMATION TECHNOLOGY     24  21.0  Failed
8           31      ZAINAB AHMED        COMPUTER SCIENCE     25   NaN  Passed
9           33         USMAN ALI        COMPUTER SCIENCE     25  32.0  Passed

In [81]:
df.AGE.max()

32.0

In [82]:
df.AGE.min()

17.0

In [83]:
df.AGE.argmax()

9

In [84]:
df[df.AGE >= 20][["NAMES","DEPARTMENT"]]

NAMES              DEPARTMENT
0      ABDIL MOIZ          CYBER SECURITY
2     SALMA AIJAZ          CYBER SECURITY
3  MATIULLAH KHAN          CYBER SECURITY
6      AHMED KHAN  INFORMATION TECHNOLOGY
7       FAIZA ALI  INFORMATION TECHNOLOGY
9       USMAN ALI        COMPUTER SCIENCE

In [85]:
df.AGE.isnull()

0    False
1     True
2    False
3    False
4     True
5    False
6    False
7    False
8     True
9    False
Name: AGE, dtype: bool

In [86]:
df.AGE.isnull().sum()

3

In [87]:
df.DEPARTMENT.unique()

array(['CYBER SECURITY', 'SOFTWARE ENGINEERING', 'INFORMATION TECHNOLOGY',
       'COMPUTER SCIENCE'], dtype=object)

In [90]:
df.DEPARTMENT.value_counts(dropna=True)

DEPARTMENT
CYBER SECURITY            4
SOFTWARE ENGINEERING      2
INFORMATION TECHNOLOGY    2
COMPUTER SCIENCE          2
Name: count, dtype: int64

In [91]:
df.BATCH.unique()


array([22, 23, 24, 25], dtype=int64)

In [92]:
df.BATCH.value_counts()

BATCH
22    4
23    2
24    2
25    2
Name: count, dtype: int64

In [97]:
sales = pd.read_excel("SaleData.xlsx")

In [98]:
sales

OrderDate   Region  Manager   SalesMan          Item   Units  Unit_price  \
0  2018-01-06     East   Martha  Alexander    Television   95.00    1198.000   
1  2018-01-23  Central  Hermann     Shelli  Home Theater   50.00     500.000   
2  2018-02-09  Central  Hermann       Luis    Television   36.00    1198.000   
3  2018-02-26  Central  Timothy      David    Cell Phone   27.00     225.000   
4  2018-03-15     West  Timothy    Stephen    Television   56.00    1198.000   
5  2018-04-01     East   Martha  Alexander  Home Theater   60.00     500.000   
6  2018-04-18  Central   Martha     Steven    Television   75.00    1198.000   
7  2018-05-05  Central  Hermann       Luis    Television   90.00    1198.000   
8  2018-05-22     West  Douglas    Michael    Television   32.00    1198.000   
9  2018-06-08     East   Martha  Alexander  Home Theater   60.00     500.000   
10 2018-06-25  Central  Hermann      Sigal    Television   90.00    1198.000   
11 2018-07-12     East   Martha      Diana  Home Theater   29.00     500.000   
12 2018-07-29     East  Douglas      Karen  Home Theater   81.00     500.000   
13 2018-08-15     East   Martha  Alexander    Television   35.00    1198.000   
14 2018-09-01  Central  Douglas       John          Desk    2.00     125.000   
15 2018-09-18     East   Martha  Alexander   Video Games   16.00      58.500   
16 2018-10-05  Central  Hermann      Sigal  Home Theater   28.00     500.000   
17 2018-10-22     East   Martha  Alexander    Cell Phone   64.00     225.000   
18 2018-11-08     East  Douglas      Karen    Cell Phone   15.00     225.000   
19 2018-11-25  Central  Hermann     Shelli   Video Games   96.00      58.500   
20 2018-12-12  Central  Douglas       John    Television   67.00    1198.000   
21 2018-12-29     East  Douglas      Karen   Video Games   74.00      58.500   
22 2019-01-15  Central  Timothy      David  Home Theater   46.00     500.000   
23 2019-02-01  Central  Douglas       John  Home Theater   87.00     500.000   
24 2019-02-18     East   Martha  Alexander  Home Theater    4.00     500.000   
25 2019-03-07     West  Timothy    Stephen  Home Theater    7.00     500.000   
26 2019-03-24  Central  Hermann       Luis   Video Games   50.00      58.500   
27 2019-04-10  Central   Martha     Steven    Television   66.00    1198.000   
28 2019-04-27     East   Martha      Diana    Cell Phone   96.00     225.000   
29 2019-05-14  Central  Timothy      David    Television   53.00    1198.000   
30 2019-05-31  Central  Timothy      David  Home Theater   80.00     500.000   
31 2019-06-17  Central  Hermann     Shelli          Desk    5.00     125.000   
32 2019-07-04     East   Martha  Alexander   Video Games   62.00      58.500   
33 2019-07-21  Central  Hermann      Sigal   Video Games   55.00      58.500   
34 2019-08-07  Central  Hermann     Shelli   Video Games   42.00      58.500   
35 2019-08-24     West  Timothy    Stephen          Desk    3.00     125.000   
36 2019-09-10  Central  Timothy      David    Television    7.00    1198.000   
37 2019-09-27     West  Timothy    Stephen    Cell Phone   76.00     225.000   
38 2019-10-14     West  Douglas    Michael  Home Theater   57.00     500.000   
39 2019-10-31  Central   Martha     Steven    Television   14.00    1198.000   
40 2019-11-17  Central  Hermann       Luis  Home Theater   11.00     500.000   
41 2019-12-04  Central  Hermann       Luis  Home Theater   94.00     500.000   
42 2019-12-21  Central   Martha     Steven  Home Theater   28.00     500.000   
43        NaT      NaN      NaN        NaN           NaN  278.00    1125.000   
44        NaT      NaN      NaN        NaN           NaN   34.75     140.625   

     Sale_amt  
0   113810.00  
1    25000.00  
2    43128.00  
3     6075.00  
4    67088.00  
5    30000.00  
6    89850.00  
7   107820.00  
8    38336.00  
9    30000.00  
10  107820.00  
11   14500.00  
12   40500.00  
13   41930.00  
14     250.00  
15     936.00  
16   14000.00  
17   14400.00  
18    3375.00  
19 

In [99]:
sales.Region.unique()

array(['East', 'Central', 'West', nan], dtype=object)

In [102]:
sales.Region.value_counts(dropna=False)

Region
Central    24
East       13
West        6
NaN         2
Name: count, dtype: int64